[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "groq>=0.22.0",
    "python-dotenv>=1.1.0",
    "serpapi>=0.1.5",
]
